
import Link from "next/link";

import Head from "next/head";
import Avatar0 from "@/assets/images/avatar0.jpg";
import Avatar1 from "@/assets/images/avatar1.jpg";
import Shoe from "@/assets/images/shoe0.jpg";
import Image from "next/image";

const Vendor= () => {
  return (
    <>
      <Head>
        <title>ShopperCart - Stores</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <section className="lg:pt-20 pt-32 pb-20 lg:px-16 sm:px-8 px-6">
        <div className="grid lg:grid-cols-8 sm:grid-cols-8 grid-cols-2 gap-8">
          <div className="lg:col-span-2 sm:col-span-4 col-span-2">
            <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
              <div className="w-full h-48 overflow-hidden">
                <Image
                  src={Shoe}
                  alt="Shoe"
                  className="w-full h-full object-cover transition-all duration-150 scale-110 hover:scale-100"
                />
              </div>

              <div className="px-4 mt-4">
                <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                  <Link
                    href=""
                    className="underline decoration-wavy decoration-green-300"
                  >
                    Lg smart tv
                  </Link>
                </h1>
                <h2 className="font-quicksand text-sm mt-2 text-slate-600 capitalize">
                  Men clothing
                </h2>
              </div>
            </div>
          </div>
          <div className="lg:col-span-2 sm:col-span-4 col-span-2">
            <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
              <div className="w-full h-48 overflow-hidden">
                <Image
                  src={Shoe}
                  alt="Shoe"
                  className="w-full h-full object-cover transition-all duration-150 scale-110 hover:scale-100"
                />
              </div>

              <div className="px-4 mt-4">
                <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                  <Link
                    href=""
                    className="underline decoration-wavy decoration-green-300"
                  >
                    Lg smart tv
                  </Link>
                </h1>
                <h2 className="font-quicksand text-sm mt-2 text-slate-600 capitalize">
                  Men clothing
                </h2>
              </div>
            </div>
          </div>
          <div className="lg:col-span-2 sm:col-span-4 col-span-2">
            <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
              <div className="w-full h-48 overflow-hidden">
                <Image
                  src={Shoe}
                  alt="Shoe"
                  className="w-full h-full object-cover transition-all duration-150 scale-110 hover:scale-100"
                />
              </div>

              <div className="px-4 mt-4">
                <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                  <Link
                    href=""
                    className="underline decoration-wavy decoration-green-300"
                  >
                    Lg smart tv
                  </Link>
                </h1>
                <h2 className="font-quicksand text-sm mt-2 text-slate-600 capitalize">
                  Men clothing
                </h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};


export default Vendor;
