import Tv from "@/assets/images/tv.jpg";
import Shoe from "@/assets/images/shoe0.jpg";
import Image from "next/image";
import Link from "next/link";
import { NextPageWithLayout } from "../_app";
import Head from "next/head";
import type { ReactElement } from "react";
import TheNavBar from "@/components/TheNavBar";
import Footer from "@/components/Footer";
import { useRef } from "react";

const Shop: NextPageWithLayout = () => {
  const categorySection = useRef<HTMLDivElement>(null);
  const toggleCategory = () => {
    categorySection.current?.classList.toggle("hidden");
  }
  return (
    <>
      <Head>
        <title>ShopperCart - Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <section className="lg:pt-20 pt-32 pb-20 lg:px-16 sm:px-8 px-6">
        <div className="grid lg:grid-cols-10 grid-cols-8">
          <div className="lg:col-span-2 lg:block mr-6 lg:relative lg:top-0 fixed top-20 z-20 hidden" ref={categorySection}>
            <div className="sticky top-32 left-0 bg-green-50 rounded-md shadow shadow-red-50 py-8 px-6 ">
              <h1 className="font-quicksand lg:text-xl text-base font-extrabold">
                Category
              </h1>
              <ul className="my-4 flex flex-col font-quicksand font-normal text-base space-y-2 ">
                <li className="hover:underline decoration-2 decoration-wavy hover:decoration-red-300 py-2 cursor-pointer">
                  Electronics
                </li>
                <li className="hover:underline decoration-2 decoration-wavy hover:decoration-red-300 py-2 cursor-pointer">
                  Applicances
                </li>
                <li className="hover:underline decoration-2 decoration-wavy hover:decoration-red-300 py-2 cursor-pointer">
                  Furniture
                </li>
                <li className="hover:underline decoration-2 decoration-wavy hover:decoration-red-300 py-2 cursor-pointer">
                  Accessories
                </li>
                <li className="hover:underline decoration-2 decoration-wavy hover:decoration-red-300 py-2 cursor-pointer">
                  Electronics
                </li>
              </ul>
            </div>
          </div>
          <div className="lg:col-span-8 col-span-8 flex flex-col space-y-3">
            <div className="flex flex-row items-center justify-between">
              <h1 className="font-quicksand text-xl font-extrabold">
                Products
              </h1>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="22"
                height="22"
                fill="currentColor"
                className="bi bi-filter-circle sm:hidden block"
                viewBox="0 0 16 16"
                onClick={toggleCategory}
              >
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                <path d="M7 11.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm-2-3a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-2-3a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5z" />
              </svg>
            </div>
            <div className="grid lg:grid-cols-9 sm:grid-cols-8 grid-cols-2 gap-8">
              <div className="lg:col-span-3 sm:col-span-4 col-span-2">
                <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
                  <div className="w-full h-48">
                    <Image
                      src={Shoe}
                      alt="Shoe"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="absolute top-44 right-8 w-12 h-12 rounded-full bg-white grid place-content-center shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] shadow-green-400">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      fill="currentColor"
                      className="bi bi-cart3 fill-green-400"
                      viewBox="0 0 16 16"
                    >
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                  </div>
                  <div className="px-4 mt-8">
                    <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                      <Link
                        href=""
                        className="underline decoration-wavy decoration-green-300"
                      >
                        Lg smart tv
                      </Link>
                    </h1>
                    <div className="flex flex-row items-center flex-wrap justify-between mt-2">
                      <h2 className="font-quicksand text-[0.87em] text-slate-600 capitalize">
                        Men clothing
                      </h2>
                      <h3 className="font-quicksand text-[0.87em] text-slate-600 px-6 py-2 bg-gray-50 rounded-lg  font-semibold">
                        #89844
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-3 sm:col-span-4 col-span-2">
                <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
                  <div className="w-full h-48">
                    <Image
                      src={Shoe}
                      alt="Shoe"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="absolute top-44 right-8 w-12 h-12 rounded-full bg-white grid place-content-center shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] shadow-green-400">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      fill="currentColor"
                      className="bi bi-cart3 fill-green-400"
                      viewBox="0 0 16 16"
                    >
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                  </div>
                  <div className="px-4 mt-8">
                    <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                      <Link
                        href="/product/2"
                        className="underline decoration-wavy decoration-green-300"
                      >
                        Lg smart tv
                      </Link>
                    </h1>
                    <div className="flex flex-row items-center flex-wrap justify-between mt-2">
                      <h2 className="font-quicksand text-[0.87em] text-slate-600 capitalize">
                        Men clothing
                      </h2>
                      <h3 className="font-quicksand text-[0.87em] text-slate-600 px-6 py-2 bg-gray-50 rounded-lg  font-semibold">
                        #89844
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-3 sm:col-span-4 col-span-2">
                <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
                  <div className="w-full h-48">
                    <Image
                      src={Shoe}
                      alt="Shoe"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="absolute top-44 right-8 w-12 h-12 rounded-full bg-white grid place-content-center shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] shadow-green-400">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      fill="currentColor"
                      className="bi bi-cart3 fill-green-400"
                      viewBox="0 0 16 16"
                    >
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                  </div>
                  <div className="px-4 mt-8">
                    <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                      <Link
                        href=""
                        className="underline decoration-wavy decoration-green-300"
                      >
                        Lg smart tv
                      </Link>
                    </h1>
                    <div className="flex flex-row items-center flex-wrap justify-between mt-2">
                      <h2 className="font-quicksand text-[0.87em] text-slate-600 capitalize">
                        Men clothing
                      </h2>
                      <h3 className="font-quicksand text-[0.87em] text-slate-600 px-6 py-2 bg-gray-50 rounded-lg  font-semibold">
                        #89844
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-3 sm:col-span-4 col-span-2">
                <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
                  <div className="w-full h-48">
                    <Image
                      src={Shoe}
                      alt="Shoe"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="absolute top-44 right-8 w-12 h-12 rounded-full bg-white grid place-content-center shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] shadow-green-400">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      fill="currentColor"
                      className="bi bi-cart3 fill-green-400"
                      viewBox="0 0 16 16"
                    >
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                  </div>
                  <div className="px-4 mt-8">
                    <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                      <Link
                        href=""
                        className="underline decoration-wavy decoration-green-300"
                      >
                        Lg smart tv
                      </Link>
                    </h1>
                    <div className="flex flex-row items-center flex-wrap justify-between mt-2">
                      <h2 className="font-quicksand text-[0.87em] text-slate-600 capitalize">
                        Men clothing
                      </h2>
                      <h3 className="font-quicksand text-[0.87em] text-slate-600 px-6 py-2 bg-gray-50 rounded-lg  font-semibold">
                        #89844
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-3 sm:col-span-4 col-span-2">
                <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
                  <div className="w-full h-48">
                    <Image
                      src={Shoe}
                      alt="Shoe"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="absolute top-44 right-8 w-12 h-12 rounded-full bg-white grid place-content-center shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] shadow-green-400">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      fill="currentColor"
                      className="bi bi-cart3 fill-green-400"
                      viewBox="0 0 16 16"
                    >
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                  </div>
                  <div className="px-4 mt-8">
                    <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                      <Link
                        href=""
                        className="underline decoration-wavy decoration-green-300"
                      >
                        Lg smart tv
                      </Link>
                    </h1>
                    <div className="flex flex-row items-center flex-wrap justify-between mt-2">
                      <h2 className="font-quicksand text-[0.87em] text-slate-600 capitalize">
                        Men clothing
                      </h2>
                      <h3 className="font-quicksand text-[0.87em] text-slate-600 px-6 py-2 bg-gray-50 rounded-lg  font-semibold">
                        #89844
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-3 sm:col-span-4 col-span-2">
                <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
                  <div className="w-full h-48">
                    <Image
                      src={Shoe}
                      alt="Shoe"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="absolute top-44 right-8 w-12 h-12 rounded-full bg-white grid place-content-center shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] shadow-green-400">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      fill="currentColor"
                      className="bi bi-cart3 fill-green-400"
                      viewBox="0 0 16 16"
                    >
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                  </div>
                  <div className="px-4 mt-8">
                    <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                      <Link
                        href=""
                        className="underline decoration-wavy decoration-green-300"
                      >
                        Lg smart tv
                      </Link>
                    </h1>
                    <div className="flex flex-row items-center flex-wrap justify-between mt-2">
                      <h2 className="font-quicksand text-[0.87em] text-slate-600 capitalize">
                        Men clothing
                      </h2>
                      <h3 className="font-quicksand text-[0.87em] text-slate-600 px-6 py-2 bg-gray-50 rounded-lg  font-semibold">
                        #89844
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-3 sm:col-span-4 col-span-2">
                <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
                  <div className="w-full h-48">
                    <Image
                      src={Tv}
                      alt="Tv"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="absolute top-44 right-8 w-12 h-12 rounded-full bg-white grid place-content-center shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] shadow-green-400">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      fill="currentColor"
                      className="bi bi-cart3 fill-green-400"
                      viewBox="0 0 16 16"
                    >
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                  </div>
                  <div className="px-4 mt-8">
                    <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                      <Link
                        href=""
                        className="underline decoration-wavy decoration-green-300"
                      >
                        Lg smart tv
                      </Link>
                    </h1>
                    <div className="flex flex-row items-center flex-wrap justify-between mt-2">
                      <h2 className="font-quicksand text-[0.87em] text-slate-600 capitalize">
                        Men clothing
                      </h2>
                      <h3 className="font-quicksand text-[0.87em] text-slate-600 px-6 py-2 bg-gray-50 rounded-lg  font-semibold">
                        #89844
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-3 sm:col-span-4 col-span-2">
                <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
                  <div className="w-full h-48">
                    <Image
                      src={Shoe}
                      alt="Shoe"
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="absolute top-44 right-8 w-12 h-12 rounded-full bg-white grid place-content-center shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] shadow-green-400">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="20"
                      height="20"
                      fill="currentColor"
                      className="bi bi-cart3 fill-green-400"
                      viewBox="0 0 16 16"
                    >
                      <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                  </div>
                  <div className="px-4 mt-8">
                    <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
                      <Link
                        href=""
                        className="underline decoration-wavy decoration-green-300"
                      >
                        Lg smart tv
                      </Link>
                    </h1>
                    <div className="flex flex-row items-center flex-wrap justify-between mt-2">
                      <h2 className="font-quicksand text-[0.87em] text-slate-600 capitalize">
                        Men clothing
                      </h2>
                      <h3 className="font-quicksand text-[0.87em] text-slate-600 px-6 py-2 bg-gray-50 rounded-lg  font-semibold">
                        #89844
                      </h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

Shop.getLayout = function PageLayout(page: ReactElement) {
  return (
    <>
      <TheNavBar />
      {page}
      <Footer />
    </>
  );
};

export default Shop;

// <div className="lg:col-span-3 col-span-2">
//   <div className="shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] rounded-md pb-6 relative">
//     <div className="w-full h-48">
//       <Image src={Shoe} alt="Shoe" className="w-full h-full object-cover" />
//     </div>
//     <div className="absolute top-44 right-8 w-12 h-12 rounded-full bg-white grid place-content-center shadow-[0_0px_4px_-1.76px_rgba(0,0,0,0.3)] shadow-green-400">
//       <svg
//         xmlns="http://www.w3.org/2000/svg"
//         width="20"
//         height="20"
//         fill="currentColor"
//         className="bi bi-cart3 fill-green-400"
//         viewBox="0 0 16 16"
//       >
//         <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
//       </svg>
//     </div>
//     <div className="px-4 mt-8">
//       <h1 className="font-quicksand text-base text-slate-800 font-semibold capitalize">
//         <Link
//           href=""
//           className="underline decoration-wavy decoration-green-300"
//         >
//           Lg smart tv
//         </Link>
//       </h1>
//       <div className="flex flex-row items-center flex-wrap justify-between mt-2">
//         <h2 className="font-quicksand text-[0.87em] text-slate-600 capitalize">
//           Men clothing
//         </h2>
//         <h3 className="font-quicksand text-[0.87em] text-slate-600 px-6 py-2 bg-gray-50 rounded-lg  font-semibold">
//           #89844
//         </h3>
//       </div>
//     </div>
//   </div>
// </div>;
